version: "3.8"

services:
  frontend-user-side:
    image: buihien0109/frontend-blog-user-side:latest
    ports:
      - "8886:80"
    depends_on:
      - backend-side
      - frontend-admin-side
    networks:
      - app-blog-network

  frontend-admin-side:
    image: buihien0109/frontend-blog-admin-side:latest
    depends_on:
      - backend-blog-side
    networks:
      - app-blog-network

  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/init.sql
      - data_blog:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
    networks:
      - app-blog-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "86:80"
    environment:
      PMA_HOST: mysql 
      MYSQL_ROOT_PASSWORD: 123
    networks:
      - app-blog-network

  backend-side:
    image: buihien0109/backend-blog-side:latest
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/db-blog?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123
    networks:
      - app-blog-network

volumes:
  data_blog:

networks:
  app-blog-network:
    driver: bridge
